######### 锚点 start #######
# proxy 相关
pr:
  &pr {
    type: select,
    proxies:
      [
        默认,
        香港,
        台湾,
        日本,
        新加坡,
        美国,
        其它地区,
        全部节点,
        自动选择,
        DIRECT,
      ],
  }

#这里是订阅更新和延迟测试相关的
p:
  &p {
    type: http,
    interval: 3600,
    health-check:
      {
        enable: true,
        url: https://www.gstatic.com/generate_204,
        interval: 300,
      },
  }

use: &use
  type: select
  use:
    - provider1
  # - provider2
  # - provider3

######### 锚点 end #######

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    <<: *p
    url: ""

  provider2:
    <<: *p
    url: ""

  provider3:
    <<: *p
    url: ""

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 10090
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:7921

find-process-mode: strict
global-client-fingerprint: firefox

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - stun.*.*
    - stun.*.*.*
    - swscan.apple.com
    - mesu.apple.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.ipv6.microsoft.com"
    - teredo.*.*.*
    - teredo.*.*
    - speedtest.cros.wr.pvp.net
    - +.jjvip8.com
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
    - WORKGROUP
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - "tls://8.8.4.4#dns"
    - "tls://1.0.0.1#dns"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: engage.cloudflareclient.com
  #   port: 2408
  #   ip: "172.16.0.2/32"
  #   ipv6: "2606::1/128"        # 自行替换
  #   private-key: "private-key" # 自行替换
  #   public-key: "public-key"   # 自行替换
  #   udp: true
  #   reserved: "abba"           # 自行替换
  #   mtu: 1280
  #   dialer-proxy: "dns"
  #   remote-dns-resolve: true
  #   dns:
  #     - https://dns.cloudflare.com/dns-query

proxy-groups:
  - {
      name: 默认,
      type: select,
      proxies:
        [DIRECT, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点, 自动选择],
    }

  # - {name: dns, type: select, proxies: [DIRECT, WARP, 香港, 台湾, 日本, 新加坡, 美国, 其它地区, 全部节点, 自动选择]}  # 加入 WARP
  - {
      name: dns,
      type: select,
      proxies:
        [
          DIRECT,
          自动选择,
          默认,
          香港,
          台湾,
          日本,
          新加坡,
          美国,
          其它地区,
          全部节点,
        ],
    }

  - { name: 🕹️ Game, <<: *pr }

  - { name: 🍎 Apple, <<: *pr }

  - { name: ✈️ Telegram, <<: *pr }

  - { name: 💻 Microsoft, <<: *pr }

  - { name: 🤖 Google, <<: *pr }

  - { name: 📺 BiliBili, <<: *pr }

  - { name: ⚡ 下载, <<: *pr }

  - { name: 🚫 广告净化, type: select, proxies: [PASS, REJECT] }

  - {
      name: 📰 国内网站,
      type: select,
      proxies:
        [
          DIRECT,
          默认,
          香港,
          台湾,
          日本,
          新加坡,
          美国,
          其它地区,
          全部节点,
          自动选择,
        ],
    }

  - { name: 🐟 漏网之鱼, <<: *pr }

  #分隔,下面是地区分组
  - { name: 香港, <<: *use, filter: "(?i)港|hk|hongkong|hong kong" }

  - { name: 台湾, <<: *use, filter: "(?i)台|tw|taiwan" }

  - { name: 日本, <<: *use, filter: "(?i)日本|jp|japan" }

  - { name: 美国, <<: *use, filter: "(?i)美|us|unitedstates|united states" }

  - { name: 新加坡, <<: *use, filter: "(?i)(新|sg|singapore)" }

  - {
      name: 其它地区,
      <<: *use,
      filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*",
    }

  - { name: 全部节点, <<: *use }

  - { name: 自动选择, <<: *use, tolerance: 2, type: url-test }

rules:
  - RULE-SET,Lan,DIRECT
  - RULE-SET,SteamCN,⚡ 下载
  - RULE-SET,GameDownloadCN,⚡ 下载
  - RULE-SET,GameDownload,⚡ 下载
  - RULE-SET,Game,🕹️ Game
  - RULE-SET,Download,⚡ 下载
  - RULE-SET,PrivateTracker,⚡ 下载
  - RULE-SET,Apple,🍎 Apple
  - RULE-SET,Apple_Domain,🍎 Apple
  - RULE-SET,Telegram,✈️ Telegram
  - AND,((NOT,((RULE-SET,Direct))),(OR,((RULE-SET,Advertising),(RULE-SET,Advertising_Domain)))),🚫 广告净化
  - RULE-SET,GitHub,💻 Microsoft
  - RULE-SET,Microsoft,💻 Microsoft
  - RULE-SET,YouTube,🤖 Google
  - RULE-SET,Google,🤖 Google
  - RULE-SET,BiliBili,📺 BiliBili
  - RULE-SET,Bahamut,台湾
  - RULE-SET,ChinaMax,📰 国内网站
  - RULE-SET,ChinaMax_IP,📰 国内网站
  - RULE-SET,ChinaMax_Domain,📰 国内网站
  - MATCH,🐟 漏网之鱼 # 规则之外的

rule-providers:
  Direct: # 广告放行
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Direct/Direct.yaml"
    interval: 86400
    path: ./ruleset/Direct.yaml

  Advertising_Domain:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Advertising/Advertising_Domain.yaml"
    interval: 86400
    path: ./ruleset/Advertising_Domain.yaml

  Advertising:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Advertising/Advertising.yaml"
    interval: 86400
    path: ./ruleset/Advertising.yaml

  GitHub:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml"
    interval: 86400
    path: ./ruleset/GitHub.yaml

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
    interval: 86400
    path: ./ruleset/Microsoft.yaml

  Apple_Domain:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Apple/Apple_Domain.yaml"
    interval: 86400
    path: ./ruleset/Apple_Domain.yaml

  Apple:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
    interval: 86400
    path: ./ruleset/Apple.yaml

  Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Game/Game.yaml"
    interval: 86400
    path: ./ruleset/Game.yaml

  GameDownloadCN:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.yaml"
    interval: 86400
    path: ./ruleset/GameDownloadCN.yaml

  GameDownload:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Game/GameDownload/GameDownload.yaml"
    interval: 86400
    path: ./ruleset/GameDownload.yaml

  SteamCN:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.yaml"
    interval: 86400
    path: ./ruleset/SteamCN.yaml

  BiliBili:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml"
    interval: 86400
    path: ./ruleset/BiliBili.yaml

  YouTube:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    interval: 86400
    path: ./ruleset/YouTube.yaml

  Google:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Google/Google.yaml"
    interval: 86400
    path: ./ruleset/Google.yaml

  Bahamut:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.yaml"
    interval: 86400
    path: ./ruleset/Bahamut.yaml

  Telegram:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
    interval: 86400
    path: ./ruleset/Telegram.yaml

  ChinaMax_Domain: # 中国大陆 IP 地址列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml"
    path: ./ruleset/ChinaMax_Domain.yaml
    interval: 86400

  ChinaMax_IP: # 中国大陆 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_IP.yaml"
    path: ./ruleset/ChinaMax_IP.yaml
    interval: 86400

  ChinaMax: # 中国大陆 IP 地址列表
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax.yaml"
    path: ./ruleset/ChinaMax.yaml
    interval: 86400

  Lan:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/Lan.yaml
    interval: 86400

  Download:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/Download/Download.yaml"
    path: ./ruleset/Download.yaml
    interval: 86400

  PrivateTracker:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/HAMAN23333/ios_rule_script@master/rule/Clash/PrivateTracker/PrivateTracker.yaml"
    path: ./ruleset/PrivateTracker.yaml
    interval: 86400
