# Merge Template for clash verge
# The `Merge` format used to enhance profile

mode: rule
ipv6: true
log-level: info
allow-lan: true
mixed-port: 19119
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:2952

find-process-mode: strict
global-client-fingerprint: firefox

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: []
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - "tls://8.8.4.4#DNS"
    - "tls://1.0.0.1#DNS"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:ChinaMax,ChinaMax_Domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    # 直连
    "rule-set:Lan":
      - 192.168.1.1 
