# Merge Template for clash verge
# The `Merge` format used to enhance profile

mode: rule
unified-delay: true
tcp-concurrent: true

profile:
  store-selected: true
  store-fake-ip: true

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter: 
<<<<<<< HEAD:Config/Clash Verge/Mixin.yaml
    - '*'
    - '*.lan'
    - '*.local'
    - lb._dns-sd._udp.*.in-addr.arpa
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - '+.nvidia.com'
    - '+.nvidia.cn'
    - '+.nvgs.nvidia.com'
    - '+.nvgs.nvidia.cn'
    - epdg.epc.aptg.com.tw
    - epdg.epc.att.net
    - epdg.mobileone.net.sg
    - primgw.vowifina.spcsdns.net
    - swu-loopback-epdg.qualcomm.com
    - vowifi.jio.com
    - weconnect.globe.com.ph
    - wlan.three.com.hk
    - wo.vzwwo.com
    - epdg.epc.*.pub.3gppnetwork.org
    - ss.epdg.epc.*.pub.3gppnetwork.org
    - dengon.docomo.ne.jp
    - dlinkap
    - dlinkrouter
    - edimax.setup
    - fritz.box
    - gateway.2wire.net
    - miwifi.com
    - my.firewall
    - my.keenetic.net
    - netis.cc
    - pocket.wifi
    - repeater.asus.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - tplinkrepeater.net
    - oppowifi.com
    - myrepeater.net
    - mywifi.net
    - setup.pix-link.net
    - tplinkdeco.net
    - tplinkextender.net
    - router.asus.com
    - www.asusrouter.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
=======
    - "*"
    - "+.lan"
    - "+.local"
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - localhost.ptlogin2.qq.com
>>>>>>> 3d94ddf (Update Mixin.yaml):Config/clash-verge/mixin.yaml
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 'https://1.1.1.1/dns-query#DNS'
    - 'https://dns.google/dns-query#DNS'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
<<<<<<< HEAD:Config/Clash Verge/Mixin.yaml
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
=======
    "geosite:category-ads-all": rcode://success
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
>>>>>>> 3d94ddf (Update Mixin.yaml):Config/clash-verge/mixin.yaml
