# Merge Template for clash verge
# The `Merge` format used to enhance profile
prepend-proxies:
  - name: "WARP"
    type: socks5
    server: 127.0.0.1
    port: 7950

proxy-groups:
  - name: 默认
    type: select
    proxies:
      - WARP
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - 全部节点
      - 自动选择
      - DIRECT
  - name: DNS
    type: select
    proxies:
      - DIRECT
      - WARP
      - 自动选择
      - 默认
  - name: CDN
    type: select
    proxies:
      - DIRECT
      - WARP
      - 自动选择
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
  - name: 🕹️ Game
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - DIRECT
  - name: 🍎 Apple
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - DIRECT
  - name: ✈️ Telegram
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
  - name: 💻 Microsoft
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - DIRECT
  - name: 🤖 Google
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
  - name: 📺 BiliBili
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 新加坡
      - DIRECT
  - name: ⚡ 下载
    type: select
    proxies:
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
      - DIRECT
  - name: 🚫 广告净化
    type: select
    proxies:
      - PASS
      - REJECT
  - name: 📰 国内网站
    type: select
    proxies:
      - DIRECT
      - 默认
      - 香港
      - 台湾
      - 日本
      - 新加坡
      - 美国
      - 其它地区
  - name: 香港
    type: select
    proxies:
      - REJECT
  - name: 台湾
    type: select
    proxies:
      - REJECT
  - name: 日本
    type: select
    proxies:
      - REJECT
  - name: 美国
    type: select
    proxies:
      - REJECT
  - name: 新加坡
    type: select
    proxies:
      - REJECT
  - name: 其它地区
    type: select
    proxies:
      - REJECT
  - name: 全部节点
    type: select
    proxies:
      - REJECT
  - name: 自动选择
    type: url-test
    tolerance: 2
    proxies:
      - REJECT

rules:
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
  - GEOSITE,private,DIRECT
  - GEOSITE,category-ads-all,🚫 广告净化
  - GEOSITE,cloudflare,CDN
  - GEOSITE,apple@cn,CDN
  - GEOSITE,microsoft@cn,CDN
  - GEOSITE,category-games@cn,CDN
  - GEOSITE,category-games,🕹️ Game
  - GEOSITE,github,💻 Microsoft
  - GEOSITE,microsoft,💻 Microsoft
  - GEOSITE,youtube,🤖 Google
  - GEOSITE,google,🤖 Google
  - GEOSITE,apple,🍎 Apple
  - GEOSITE,bilibili,📺 BiliBili
  - GEOSITE,telegram,✈️ Telegram
  - GEOSITE,tracker,⚡ 下载
  - RULE-SET,Download,⚡ 下载
  - GEOSITE,bahamut,台湾
  - GEOSITE,geolocation-!cn,默认

  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cloudflare,CDN
  - GEOIP,google,🤖 Google
  - GEOIP,telegram,✈️ Telegram

  - GEOSITE,CN,📰 国内网站
  - GEOIP,CN,📰 国内网站
  - MATCH,默认 # 规则之外的

rule-providers:

  Download:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Download/Download.yaml"
    path: ./ruleset/Download.yaml
    interval: 86400