# Merge Template for clash verge
# The `Merge` format used to enhance profile

mode: rule
unified-delay: true
tcp-concurrent: true

find-process-mode: strict

profile:
  store-selected: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: 
    - '*'
    - '+.lan'
    - '+.local'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - '+.nvidia.com'
    - '+.nvidia.cn'
    - '+.nvgs.nvidia.com'
    - '+.nvgs.nvidia.cn'
    - router.asus.com
    - www.asusrouter.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - WORKGROUP
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - 'https://1.1.1.1/dns-query#DNS'
    - 'https://dns.google/dns-query#DNS'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "rule-set:ChinaMax,ChinaMax_Domain":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "rule-set:Lan":
      - 192.168.50.1
